server:
  port: 8080
logging:
  level:
    org:
      springframework:
        web: TRACE
      hibernate: info
      hibernate.type: trace
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher