gottabeio:
  siteName: GottaBe.io
  siteAddress: 'https://gottabe.io/'
  debug: true
  cli:
    client_id: ccb81ad6-62b7-407a-8a95-a8c31f656307
    token:
      expiration: 0
      refresh: 0
  server:
    client_id: 4dae1aa5-8200-4f06-ba0c-8786f64f01c0
    client_password: ac1ecd02-9e0c-4883-a0f0-c62dd5cccdc3
    token:
      expiration: 36000
      refresh: 604800
  config:
    autoActivate: true
    salty:
      password: ${PASSWORD_SALTY:salty}
      activation: ${ACTIVATION_SALTY:salty}
      recover: ${RECOVER_SALTY:salty}
    mail:
      smtpHost: ${SMTP_HOST}
      smtpPort: ${SMTP_PORT}
      fromMail: ${MAIL_FROM}
      user: ${MAIL_USER}
      pass: ${MAIL_PASS}
  store:
    useS3: false
    base:
      dir: ./data
    tokens: jdbc
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: ${DATABASE_URL:jdbc:postgresql://localhost/gottabe}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:postgres}
    testWhileIdle: true
    validationQuery: SELECT 1
    platform: postgres
  jackson:
    serialization-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: io.gottabe.commons.util.CustomPostgreSQL10Dialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/api/.well-known/jwks.json
flyway:
  validateOnMigrate: false
